
# Site settings
title: Nina Chen
email: ninachen@gmail.com
description: Welcome to my page!
baseurl: "/ncheneld.github.io/"
url: "localhost:4000"

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
