source 'https://rubygems.org'
# gem 'nokogiri'
# gem 'rack', '~> 2.0.1'
# gem 'rspec'
gem 'jekyll', '~>3.3'
gem 'jekyll-theme-leap-day'
gem 'wdm', '~> 0.1.0'

gem 'kramdown-parser-gfm'
# gem 'kramdown', '~> 2.3.0'
# gem 'coderay', '~> 1.0.0'
# gem 'itextomml', '~> 1.5'
# gem 'minitest', '~> 5.0'
# gem 'prawn', '~> 2.0'
# gem 'ritex', '~> 1.0'
# gem 'rouge', '~> 3.22.0'
# gem 'stringex', '~> 1.5.1'